---
- name: Ajouter un mot de passe à l'utilisateur Pierre
  hosts: localhost
  become: true
  tasks:
    - name: Définir le mot de passe pour l'utilisateur pierre
      user:
        name: pierre
        password: "{{ newpass | password_hash('sha512') }}"
        update_password: always
    
    - name: Vérifier que l'utilisateur peut se connecter
      shell: id pierre
      register: user_verification
    
    - name: Afficher la confirmation
      debug:
        msg: "Mot de passe défini pour l'utilisateur pierre : {{ user_verification.stdout }}"