---
- name: Installation d'Apache2
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Installer apache2
      apt:
        name: apache2
        state: present
        update_cache: yes