---
- name: Planifier une tâche automatique avec cron
  hosts: localhost
  become: true
  tasks:
    - name: Mettre à jour la liste des paquets APT
      apt:
        update_cache: yes
    
    - name: Installer le paquet cron
      apt:
        name: cron
        state: present
    
    - name: Planifier l'exécution de script1.sh tous les lundis à 15h10
      cron:
        name: "Exécution script1 hebdomadaire"
        minute: "10"
        hour: "15"
        weekday: "1"
        job: "/root/script1.sh"
        user: root
    
    - name: Afficher les tâches cron actuelles
      shell: crontab -l
      register: crontab_list
      ignore_errors: yes
    
    - name: Montrer le crontab
      debug:
        msg: "{{ crontab_list.stdout_lines }}"