---
- name: Modifier les permissions d'un fichier
  hosts: localhost
  tasks:
    - name: Changer les permissions du fichier vinci (ajout écriture pour tous)
      file:
        path: /root/vinci
        mode: '0666'
        state: file
    
    - name: Vérifier les nouvelles permissions
      stat:
        path: /root/vinci
      register: file_permissions
    
    - name: Afficher les permissions
      debug:
        msg: "Permissions du fichier : {{ file_permissions.stat.mode }}"